services:
  - type: web
    name: hundredtools-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js

    aptPackages:
      - libreoffice
      - ghostscript